default_context:
  project_name: 'fullstack_fastapi_template'
  project_slug: 'fullstack_fastapi_template'
  domain_main: 'fullstack_fastapi_template.com'
  domain_staging: 'stag.fullstack_fastapi_template.com'
  docker_swarm_stack_name_main: 'fullstack_fastapi_template-com'
  docker_swarm_stack_name_staging: 'stag-fullstack_fastapi_template-com'
  secret_key: 'changethis'
  first_superuser: 'admin@admin.com'
  first_superuser_password: 'admin'
  backend_cors_origins: '[\"http://localhost\"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@fullstack_fastapi_template.com'
  postgres_password: 'admin'
  pgadmin_default_user: 'admin@admin.com'
  pgadmin_default_user_password: 'admin'
  traefik_constraint_tag: 'fullstack_fastapi_template.com'
  traefik_constraint_tag_staging: 'stag.fullstack_fastapi_template.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:admin'
  sentry_dsn: ''
  docker_image_prefix: 'fast_api_template'
  docker_image_backend: 'fast_api_templatebackend'
  docker_image_celeryworker: 'fast_api_templateceleryworker'
  docker_image_frontend: 'fast_api_templatefrontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
